# .github/workflows/lint.yml

name: Lint and Type Check

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ruff-check:
    name: Ruff Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install locked runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/lock.txt

      - name: Install Ruff
        run: |
          pip install ruff

      - name: Run Ruff (Check for style violations)
        run: ruff check . --exit-zero

  black-check:
    name: Black Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install locked runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/lock.txt

      - name: Install Black
        run: pip install black

      - name: Run Black (Check)
        run: black --check .

  mypy-check:
    name: Mypy Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install locked runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/lock.txt

      - name: Install Dependencies
        run: |
          pip install mypy

      - name: Run Mypy
        run: mypy .