jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install .[dev]
      - run: python -m unittest discover -v
      - run: |
          pip install dunamai
          dunamai from git --style pep440 --strict
